### ISSUE TITLE
wishlist: pen borders

### ISSUE THREAD

**Issue by eglash** [CSnap/CSnap#13]
Pen borders are really important for drawing many cultural patterns. The pen border block should function similar to the pen color block. The borders should have 2 parameters for color and width. A third parameter should toggle on/off to determine if the borders remain constant width or change in proportion to pen width. A drop-down could be used to select which of the two borders you are changing. "Growth" of the borders should only occur inside the pen stroke, so the maximum border size is the pen width. You can see an example of border controls in our graffiti tool at http://csdt.rpi.edu/subcult/grafitti/software/flash/grapher.html -- here is an image produced by it.

![image](https://cloud.githubusercontent.com/assets/787868/3442447/2a4d0ccc-0114-11e4-8fa8-68a062907420.png)

**Comment by SillyInventor** [comment]
Done. Thanks David.
