### ISSUE TITLE
drop-downs frequently stop working; fill-in occasionally fail as well

### ISSUE THREAD

**Issue by eglash** [CSnap/CSnap#19]
Work on CSnap long enough, and you will eventually find the drop-down in a block stops working: try as you might, you cannot get a response when you click on the little black triangle.
![image](https://cloud.githubusercontent.com/assets/787868/3565340/2e0f968a-0ab6-11e4-8735-4516bece7227.png)
Occasionally a similar problem happens with fill-ins, but its not as baf.

**Comment by SillyInventor** [comment]
Fixed.

**Comment by ibara** [comment]
My hero!

**Comment by chuck211991** [comment]
Could you link the the commit it was fixed in?

**Comment by SillyInventor** [comment]
https://github.com/CSnap/CSnap/commit/b2a978a080df4427fa572e1f6ce53517ff7d0678
