### ISSUE TITLE
highest priority: need ability to scale the x,y coordinate readout so that it matches beads, stitches, etc. 

### ISSUE THREAD

**Issue by eglash** [CSnap/CSnap#28]
See https://community.csdt.rpi.edu/projects/293 for an example. Note that the user can scale beads to any size, so it would be great if there was a way to link the readout scale with that. Even better would be a way to "zoom" the stage, not just for the readout, but how the user actually interacts with the stage. That way we can use standard blocks to say "go to x=___" rather than the custom blocks in the above project (number 293).

**Comment by SillyInventor** [comment]
This was done a while ago... Thanks David.
