### ISSUE TITLE
Medium priority: Password reset option on community site

### ISSUE THREAD

**Issue by ibara** [CSnap/CSnap#29]
A number of students in Cleveland forgot their password over the course of our three days. Neither they nor I could find a password reset button. Charles told me I could log into the admin panel and reset user passwords that way but I was unable to log in to the admin panel. We should give users the option of resetting passwords themselves anyway (we do collect their emails after all).

**Comment by chuck211991** [comment]
Moved issue to the community; see https://github.com/CSnap/rpi_csdt_community/issues/103
