### ISSUE TITLE
need date/time stamp on projects saved so I know if these are students from this weeks workshop or leftover from last year

### ISSUE THREAD

**Issue by eglash** [CSnap/CSnap#38]
I get a list of projects but not sure which are recent
![image](https://cloud.githubusercontent.com/assets/787868/5462510/8da6c97c-8542-11e4-8cd5-113474ed45c0.png)

**Comment by chuck211991** [comment]
Moved to the community site; see https://github.com/CSnap/rpi_csdt_community/issues/104
