### ISSUE TITLE
wishlist: protractor tool

### ISSUE THREAD

**Issue by eglash** [CSnap/CSnap#7]
It would be nice to have a protractor for measuring curves of images that the user places on the stage: http://www.ccd.rpi.edu/eglash/csdt/african/cornrow_curves/teaching/crproinstr/protractor7.htm

**Comment by SillyInventor** [comment]
You once made a project:
https://community.csdt.rpi.edu/projects/340/

Does that close this issue?

**Comment by eglash** [comment]
Yes it does
